openapi: 3.0.0
info:
  title: User API (v2)
  version: 2.0.0
  description: "New and improved endpoints for users in v2."

tags:
  - name: User Management (v2)
    description: "New features in v2, such as pagination and analytics."

paths:
  /api/v2/users/paginated:
    get:
      summary: Get paginated users
      tags:
        - User Management (v2)
      security:
        - BearerAuth: []
      description: Retrieves users with advanced pagination.
      responses:
        "200":
          description: Successfully retrieved paginated users.

  /api/v2/users/analytics:
    get:
      summary: Get user analytics
      tags:
        - User Management (v2)
      security:
        - BearerAuth: []
      description: Fetches admin-only user analytics.
      responses:
        "200":
          description: User analytics retrieved.
