openapi: 3.0.0
info:
  title: Payment API
  version: 1.0.0
paths:
  /api/v1/payments/process:
    post:
      summary: Process a payment
      tags:
        - Payment Transactions
      description: Handles a new payment transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 100.50
                currency:
                  type: string
                  example: "USD"
                userId:
                  type: string
                  example: "12345"
      responses:
        "200":
          description: Payment processed successfully.
        "400":
          description: Invalid payment data.
  /api/v1/payments/{id}:
    get:
      summary: Get payment details
      tags:
        - Payment Transactions
      description: Fetches the details of a specific payment.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "abc123"
      responses:
        "200":
          description: Payment details retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "abc123"
                  amount:
                    type: number
                    example: 100.50
                  status:
                    type: string
                    example: "Completed"
        "404":
          description: Payment not found.
